### ISSUE TITLE
Calculating intrinsic dimensionality (Levina et al.)

### ISSUE THREAD

**Issue by jonaschn** [amritbhanu/Dodge#1]
I could not find your analysis of intrinsic dimensionality that is mentioned in the paper.
I am interested in the intrinsic dimensionality for the provided datasets (raw data).
Where can I find the source code used to reproduce the analysis of intrinsic dimensionality?

My goal is to evaluate if the usage of DODGE makes sense for my datasets.

**Comment by amritbhanu** [comment]
@jonaschn sorry for the later response, please see my co-author's work for calculating the intrinsic dimensionality here: https://github.com/amritbhanu/intrinsic_dimension

**Comment by jonaschn** [comment]
Thanks a lot!
